action_id: trunk-single-player-auto-upgrade
date: 2025-12-17 21:24:42
run: trunk upgrade cli --single-player-only -n --no-progress --on-upgrade=false --allow-daemon-start=false
run_from: ""
trigger: schedule 24h+1h
result:
  exit_code: 0
  out: ""
  err: ""
timestamp: 1766006682
full_timestamp:
  nanos: 657527000
  seconds: 1766006682
trunk_version: 1.25.0
