action_id: trunk-cache-prune
date: 2025-12-19 23:21:22
run: trunk cache prune --allow-daemon-start=false
run_from: ""
trigger: schedule 24h
result:
  exit_code: 0
  out: ""
  err: ""
timestamp: 1766186482
full_timestamp:
  nanos: 530847000
  seconds: 1766186482
trunk_version: 1.25.0
