@echo off
REM Generated by trunk tool 'checkov'
set HOME=%HOME%
if not defined HOME set HOME=
set PATH=C:\Users\guido\AppData\Local\trunk\tools\checkov\3.2.495-99d157158b0d1d9580629662c8d353e6/bin;C:\Users\guido\AppData\Local\trunk\tools\checkov\3.2.495-99d157158b0d1d9580629662c8d353e6/Scripts;C:\Users\guido\AppData\Local\trunk\tools\python\3.10.8-2211cb108575de2785d77a26a1f8d070/bin;C:\Users\guido\AppData\Local\trunk\tools\python\3.10.8-2211cb108575de2785d77a26a1f8d070;C:\Users\guido\AppData\Local\trunk\tools\git-bash\2.40.1-da0c3e1526d36e62bf43d06ec46c5052/bin;C:\Users\guido\AppData\Local\trunk\tools\git-bash\2.40.1-da0c3e1526d36e62bf43d06ec46c5052/usr/bin;%PATH%
set VIRTUAL_ENV=C:\Users\guido\AppData\Local\trunk\tools\checkov\3.2.495-99d157158b0d1d9580629662c8d353e6
set PYTHONUTF8=1

start /w /b checkov %*
