action_id: trunk-upgrade-available
date: 2025-12-20 14:07:13
run: trunk upgrade --notify --allow-daemon-start=false
run_from: ""
trigger: schedule 1h
result:
  exit_code: 2
  out: "\x1b[1m\x1b[31m✖ Trunk Internal Error: Please report this issue at https://slack.trunk.io (reference id: 03a09edad0714fd89db0dd23b61e95a6)\x1b[0m\r\n"
  err: ""
timestamp: 1766239633
full_timestamp:
  nanos: 811115000
  seconds: 1766239633
trunk_version: 1.25.0
