action_id: trunk-upgrade-available
date: 2025-11-22 13:49:17
run: trunk upgrade --notify --allow-daemon-start=false
run_from: ""
trigger: schedule 1h
result:
  exit_code: 2
  out: "\x1b[1m\x1b[31m✖ Trunk Internal Error: Please report this issue at https://slack.trunk.io (reference id: 058f6ba1d95b4cc211a0955e191cf710)\x1b[0m\r\n"
  err: ""
timestamp: 1763819357
full_timestamp:
  nanos: 720739000
  seconds: 1763819357
trunk_version: 1.25.0
