action_id: trunk-upgrade-available
date: 2025-11-22 13:49:22
run: trunk upgrade --notify --allow-daemon-start=false
run_from: ""
trigger: schedule 1h
result:
  exit_code: 2
  out: "\x1b[1m\x1b[31m✖ Trunk Internal Error: Please report this issue at https://slack.trunk.io (reference id: c084e51aed5d4d202e916d0f65a1ad46)\x1b[0m\r\n"
  err: ""
timestamp: 1763819362
full_timestamp:
  nanos: 476228000
  seconds: 1763819362
trunk_version: 1.25.0
