action_id: trunk-share-with-everyone
date: 2025-12-17 20:27:09
run: trunk config share --notify --allow-daemon-start=false
run_from: ""
trigger: schedule 24h
result:
  exit_code: 0
  out: "notifications_to_delete:\r\n  - trunk-share-with-everyone\r\n"
  err: ""
timestamp: 1766003229
full_timestamp:
  nanos: 648661000
  seconds: 1766003229
trunk_version: 1.25.0
action_output:
  notifications_to_delete:
    - trunk-share-with-everyone
